language: objective-c
osx_image: xcode7.3

script:
    - xcodebuild -workspace Dono.xcworkspace -scheme Dono -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test

branches:
  only:
    - master
