language: objective-c
os: osx
osx_image: xcode7.3

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

script:
    - set -o pipefail
    - xcodebuild clean test -workspace Dono.xcworkspace -scheme Dono -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

after_success:
    - bash <(curl -s https://codecov.io/bash)
